main: ca.mattlack.actioncompass.ActionBarCompass
name: ABC
version: 1.0.0
api-version: 1.16
author: Gravitinos
description: none
commands:
  abc:
    description: none
    usage: /<command>
  test:
  nic:
